<a href="https://colab.research.google.com/github/saue10/Day_6_Numpy_assignment/blob/main/Day6_assignment_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [4]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [5]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
arr3 = np.array([[[12,13],[14,15],[16,17]],[[18,19],[20,21],[22,23]]])
print(arr3)

[[[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [10]:
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr.shape)
print(arr2.shape)
print(arr3.shape)
print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

1
2
3
(5,)
(3, 4)
(2, 3, 2)
int64
int64
int64


In [11]:
print(arr[0],arr[4],arr[2])

10 50 30


In [12]:
print(arr2[2,3])

12


In [15]:
print(arr[1:4])

[20 30 40]


In [29]:
print(arr2[0:1,:])
print(arr2[:,1:2])
print(arr2[1:3,1:3])

[[1 2 3 4]]
[[ 2]
 [ 6]
 [10]]
[[ 6  7]
 [10 11]]


In [30]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)
print(array.shape)
reshaped_arr=array.reshape(3,4)
print(reshaped_arr)
print(reshaped_arr.shape)
reshaped_arr2 = array.reshape(2,6)
print(reshaped_arr2)
print(reshaped_arr2.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [39]:
new_arr = np.zeros((2,3))
print(new_arr)
new_arr2 = np.ones((3,2))
print(new_arr2)
new_arr3 = np.arange(0,10,2)
print(new_arr3)
new_arr4 = np.linspace(0,20,5)
print(new_arr4)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[ 0.  5. 10. 15. 20.]


In [41]:
new_arr5 = np.array([25,35,45,55,65])
new_arr6 = np.array([10,20,30,40,50])
print(new_arr5 + new_arr6)
print(new_arr5 - new_arr6)
print(new_arr5 * new_arr6)
print(new_arr5 / new_arr6)


[ 35  55  75  95 115]
[15 15 15 15 15]
[ 250  700 1350 2200 3250]
[2.5   1.75  1.5   1.375 1.3  ]


In [42]:
print(new_arr5 + 6)
print(new_arr5 * 4)
print(new_arr5 ** 2)

[31 41 51 61 71]
[100 140 180 220 260]
[ 625 1225 2025 3025 4225]


In [44]:
print(new_arr6 ** 2)
print(new_arr6 ** 0.5)
print(new_arr6 % 3)

[ 100  400  900 1600 2500]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[1 2 0 1 2]


In [47]:
student_marks = np.array([45,69,79,56,99,85,33])
print(student_marks)
print(student_marks>60)
print(student_marks[student_marks>60])

[45 69 79 56 99 85 33]
[False  True  True False  True  True False]
[69 79 99 85]


In [48]:
numbers = np.array([1,2,34,23,55,67,43,88,54,34])
print(numbers)
print(numbers%2==0)
print(numbers[numbers%2==0])

[ 1  2 34 23 55 67 43 88 54 34]
[False  True  True False False False False  True  True  True]
[ 2 34 88 54 34]


In [52]:
print(arr2+10)
a = np.array([[1],[2],[3]])
print(a)
b = np.array([12,13,14])
print(b)
print(a+b)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[1]
 [2]
 [3]]
[12 13 14]
[[13 14 15]
 [14 15 16]
 [15 16 17]]


In [54]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.median(arr))

150
30.0
50
10
30.0


In [61]:
print(np.sum(arr2))
print(np.max(arr2))
print(np.min(arr2))
print(np.mean(arr2))
print(np.median(arr2))
print(np.sum(arr2,axis=0))
print(np.sum(arr2,axis=1))
print(np.max(arr2,axis=0))
print(np.max(arr2,axis=1))
print(np.min(arr2,axis=0))
print(np.min(arr2,axis=1))
print(np.mean(arr2,axis=0))
print(np.mean(arr2,axis=1))
print(np.median(arr2,axis=0))
print(np.median(arr2,axis=1))

78
12
1
6.5
6.5
[15 18 21 24]
[10 26 42]
[ 9 10 11 12]
[ 4  8 12]
[1 2 3 4]
[1 5 9]
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]


In [64]:
students_subjectwise_marks=np.array([[70,80,90],[68,56,78],[77,89,76],[65,79,90]])
print(f"Average marks of each subject={np.mean(students_subjectwise_marks,axis=0)}")
print(f"Highest marks in each subject={np.max(students_subjectwise_marks,axis=0)}")
print(f"All marks greater than 65:{students_subjectwise_marks[students_subjectwise_marks>65]}")
print(f"Overall Average mark of all subjects={np.mean(students_subjectwise_marks)}")

Average marks of each subject=[70.  76.  83.5]
Highest marks in each subject=[77 89 90]
All marks greater than 65:[70 80 90 68 78 77 89 76 79 90]
Overall Average mark of all subjects=76.5
